[options]
server_wide_modules = base,web,iot_drivers
without_demo = True
addons_path = /mnt/enterprise-addons
admin_passwd = odoo
db_host = db
db_user = odoo
db_password = odoo
data_dir = /var/lib/odoo
http_interface = 0.0.0.0

# =============================================================
# IoT Box
# =============================================================
[iot.box]
remote_server = http://127.0.0.1:8069
db_name = main
